// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"net/http"
	"studi-kasus-restful-api/app"
	"studi-kasus-restful-api/controller"
	"studi-kasus-restful-api/middleware"
	"studi-kasus-restful-api/repository"
	"studi-kasus-restful-api/service"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	tasksRepositoryImpl := repository.NewTaskRepository()
	db := app.NewDB()
	validate := NewValidator()
	taskServiceImpl := service.NewTaskService(tasksRepositoryImpl, db, validate)
	taskControllerImpl := controller.NewTaskController(taskServiceImpl)
	router := app.NewRouter(taskControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

func NewValidator() *validator.Validate {
	return validator.New()
}

var taskSet = wire.NewSet(repository.NewTaskRepository, wire.Bind(new(repository.TasksRepository), new(*repository.TasksRepositoryImpl)), service.NewTaskService, wire.Bind(new(service.TaskService), new(*service.TaskServiceImpl)), controller.NewTaskController, wire.Bind(new(controller.TaskController), new(*controller.TaskControllerImpl)))
